# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Snow and Beer
email: no@email.yet
description: >- # this means to ignore newlines until "baseurl:"
  Not yet awesome blog.
baseurl:
url: https://maverobot.github.io
twitter_username: Maverobot
github_username: Maverobot
repository: Maverobot/maverobot.github.io
github: [metadata]
minimal_mistakes_skin: sunrise

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin
search: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

author:
  name   : "Zheng Qu"
  bio    : "A robotics enthusiast and deep learning learner, who is currently practicing dunking basketball."
  avatar : "/assets/images/bio-photo.jpg"
  email  : # optional
  uri    : "https://maverobot.github.io"
  github : "Maverobot"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
