---
baseURL: https://qurobotics.de/
languageCode: en-us
title: Qu Robotics
theme: piko
paginate: "9"
copyright:
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Zheng Qu
  description: My personal website
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: Zheng Qu
    text: Welcome to the My Personal Website
    lightNavIcon: /uploads/black_logo.png
    darkNavIcon: /uploads/green_logo.png
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: https://formsubmit.io/send/c5155564-1867-4d55-8443-c00be6d5949d
  assets:
    disableFingerprinting: false
    favicon: /uploads/green_logo.png
    favicon16x16: /uploads/green_logo.png
    favicon32x32: /uploads/green_logo.png
    apple_touch_icon: /uploads/green_logo.png
    safari_pinned_tab: /uploads/green_logo.png
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle:
    heroTitle: Hi, I'm Zheng
    heroDescription: A freelance Roboticist specializing in C++, with expertise in Linux and ROS.
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/pano_marienplatz.jpg"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section
    disableAboutSection: false
    aboutTitle: About
    aboutDescription:
    aboutImgUrl: "/uploads/self.jpeg"
    aboutContent: I am a Senior Robotics Software Engineer with a passion for creating intelligent machines. With a strong background in C++ and robotics, I have contributed to cutting-edge projects in the field. My expertise spans software development, robot behavior design, and open-source collaboration. I thrive in agile environments and am dedicated to advancing the field of robotics.
    # Portfolio Section
    disablePortfolioSection: true
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: Portfolio One.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title:
    pre: github
    url: https://github.com/maverobot
    weight: "50"
  - name: Linkedin
    title:
    pre: linkedin
    url: https://www.linkedin.com/in/zheng-qu-robotics/
    weight: "60"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
